### ISSUE TITLE
NotImplementedError on Windows Python 3.8+

### ISSUE THREAD

**Issue by anon88391** [bluet/proxybroker2#113]
Running proxybroker from CLI has been broken for me on any Python version >= 3.8

>Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pycares\__init__.py", line 99, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\aiodns\__init__.py", line 111, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\users\user\appdata\local\programs\python\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError

Apparently, Python 3.8 introduced a backwards-incompatible change to asyncio.
https://docs.python.org/3/library/asyncio-platforms.html#asyncio-platform-support
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_reader

Some people suggested adding the following code to fix it:

```
import sys

if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

<details>
<summary>Checklist</summary>

- [X] `proxybroker/cli.py`
> • At the top of the file, after the import statements, add the following code:
>   ```python
>   import sys
>   import asyncio
> 
>   if sys.platform == 'win32':
>       asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
>   ```
>   This code checks if the current platform is Windows ('win32'), and if so, it sets the event loop policy to WindowsSelectorEventLoopPolicy.

</details>

**Comment by anon88391** [comment]
Related:
https://github.com/saghul/aiodns/issues/86

**Comment by anon88391** [comment]
Didn't mean to close the issue.

Related:
https://github.com/saghul/aiodns/issues/86

**Comment by BukuBukuChagma** [comment]
running into same problem. Any solution yet?

**Comment by ziloka** [comment]
I found a solution to this. The issue is relating to aiodns not really being maintained anymore. The last time the source code was updated was 2 years ago. I believe the current solution to this is to remove aiodns and replace it with [dnspython](https://www.dnspython.org/) A library which is kept more up to date

**Comment by bluet** [comment]
@anon88391 the fix was based on your suggestion.
I don't have Windows machines for decades, and as you do and suggestions that, I applied it.

**Comment by ziloka** [comment]
> Seems like aiodns' back in the game
> https://github.com/saghul/aiodns/tags

yes, I updated the pull request just to update aiodns and aiohttp dependencies.

just need to fix a unit test that broke

**Comment by bluet** [comment]
@ziloka I just fixed the error in the unit test and dumped dependencies. Not sure about windows support.
