### ISSUE TITLE
NotImplementedError:

### ISSUE THREAD

**Issue by Vergil1000x** [bluet/proxybroker2#133]
For the given code:

import asyncio
from proxybroker import Broker

async def show(proxies):
    while True:
        proxy = await proxies.get()
        if proxy is None:
            break
        print("Found proxy: %s" % proxy)

proxies = asyncio.Queue()
broker = Broker(proxies)
tasks = asyncio.gather(broker.find(types=["HTTP", "HTTPS"], limit=10), show(proxies))

loop = asyncio.get_event_loop()
loop.run_until_complete(tasks)

I am getting  this 10 times:

Exception ignored from cffi callback <function _sock_state_cb at 0x000001A7DF3798A0>:
Traceback (most recent call last):
  File "C:\Users\koush\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycares\__init__.py", line 99, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Users\koush\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aiodns\__init__.py", line 111, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 530, in add_reader
    raise NotImplementedError
NotImplementedError: 

how to fix bro? also no proxy is showing
![Screenshot 2023-07-05 122318](https://github.com/bluet/proxybroker2/assets/137330807/c1b6e746-aa98-4be7-90af-9c41bc0e47af)

**Comment by arpitgoyall** [comment]
Same error in python 3.11

**Comment by AstolfoBestGirl1** [comment]
were you able to solve this problem, if so, how?

**Comment by ZhymabekRoman** [comment]
Doesn't reproducible error, no problem on Linux for now
