### ISSUE TITLE
help

### ISSUE THREAD

**Issue by NotASkidder** [bluet/proxybroker2#76]
loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "C:\Users\david\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\david\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\david\AppData\Local\Programs\Python\Python310\Scripts\proxybroker.exe\__main__.py", line 7, in <module>
  File "C:\Users\david\AppData\Local\Programs\Python\Python310\lib\site-packages\proxybroker\cli.py", line 386, in cli
    proxies = asyncio.Queue(loop=loop)
  File "C:\Users\david\AppData\Local\Programs\Python\Python310\lib\asyncio\queues.py", line 34, in __init__
    super().__init__(loop=loop)
  File "C:\Users\david\AppData\Local\Programs\Python\Python310\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

**Comment by bluet** [comment]
might be related to #74 

@NotASkidder can you help on testing that branch?

**Comment by afunTW** [comment]
Since PR #74 fixed the issue and merged to the master branch. This Issued should be solved.
